version=0.7.0-SNAPSHOT
group=ca.spottedleaf.moonrise
archives_base_name=moonrise

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# comma separated list for modrinth/curseforge
supported_minecraft_versions=1.21.9

# parchment param mappings and javadoc for common/neo
neoForge.parchment.parchmentArtifact=io.papermc.parchment.data:parchment-1.21.9:2025.10.02

# https://fabricmc.net/develop/
fabric_api_version=0.133.14+1.21.9

# set to false when modmenu/cloth is not updated for the current minecraft version
enable_gui=false

junit_version=5.11.3

# version ids from modrinth
fabric_lithium_version=nhc57Td2
neo_lithium_version=P5VT33Jo
