version=0.9.0-SNAPSHOT
group=ca.spottedleaf.moonrise
archives_base_name=moonrise

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# comma separated list for modrinth/curseforge
supported_minecraft_versions=1.21.11

# https://fabricmc.net/develop/
fabric_api_version=0.143.15+26.1

# set to false when modmenu/cloth is not updated for the current minecraft version
enable_gui=false

junit_version=6.0.2

# version ids from modrinth
fabric_lithium_version=mc1.21.11-0.21.2-fabric
neo_lithium_version=mc1.21.11-0.21.2-neoforge
