# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=0.0.0-SNAPSHOT
maven_group=ca.spottedleaf.moonrise
archives_base_name=moonrise

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version=b1.7.3
loader_version=0.17.2
osl_version=0.16.3

snakeyaml_version=2.3
concurrentutil_version=0.0.3
yamlconfig_version=1.0.2
