# https://fabricmc.net/develop/

[versions]
# https://maven.shedaniel.me/me/shedaniel/cloth/
cloth = "26.1.154"
fabricLoader = "0.18.6"
minecraft = "26.1.2"
# https://projects.neoforged.net/neoforged/neoforge
neoforge = "26.1.2.15-beta"
# https://projects.neoforged.net/neoforged/neoform
neoform = "26.1.2-1"

[plugins]

[libraries]
mixin = "org.spongepowered:mixin:0.8.7"
mixinExtras = "io.github.llamalad7:mixinextras-common:0.5.0"

fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricLoader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabricLoader" }
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

concurrentutil = "ca.spottedleaf:concurrentutil:0.0.10"

yamlconfig = "ca.spottedleaf:yamlconfig:1.2.0"
snakeyaml = "org.yaml:snakeyaml:2.5"

clothConfig-neoforge = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "cloth" }
clothConfig-fabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth" }
modmenu = "com.terraformersmc:modmenu:18.0.0-alpha.6"

asm = "org.ow2.asm:asm:9.8"
