name: Mod Incompatibility
description: Report an incompatibility with another mod.
title: '[Incompatibility: <NeoForge/Fabric/NeoForge & Fabric>]: Mod Name'
labels:
    - mod-incompatibility
    - needs-triage
body:
    - type: input
      id: mc_ver
      attributes:
          label: Minecraft Version
          placeholder: e.g. 1.21.1 or 1.21.2
      validations:
          required: true
    - type: input
      id: moonrise_ver
      attributes:
          label: Moonrise Version
          placeholder: e.g. 0.1.0-beta.6 or Git commit hash
      validations:
          required: true
    - type: dropdown
      id: mod_loader
      attributes:
          label: Mod Loader
          description: >-
              The mod loader(s) this conflict happens with. When selecting 'Both' it
              is expected you will submit logs for both as well. Be sure to update the
              issue title.
          options:
              - NeoForge
              - Fabric
              - Both (NeoForge and Fabric)
      validations:
          required: true
    - type: textarea
      id: logs_crashes
      attributes:
          label: Logs and Crash Reports
          description: >-
              Include links to all relevant logs and crash reports (prefer using
              https://gist.github.com/ or https://mclo.gs/). In case this is not
              applicable fill in 'N/A' (it is expected you will provide context
              below).
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional Context
          description: Provide any relevant context, including version of the conflicting mod.
      validations:
          required: true
