blank_issues_enabled: false
contact_links:
    - name: Discord
      url: https://discord.gg/tuinity
      about: If you are unsure about something or have general questions, ask in our Discord before opening an issue.
