modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/Tuinity/Moonrise"
showAsResourcePack = false
logoFile = "assets/moonrise/icon.png"

[[mods]]
modId = "moonrise"
version = "${version}"
displayName = "Moonrise"
displayURL = "https://github.com/Tuinity/Moonrise"
authors = "Spottedleaf"
description = "Optimisation mod for the dedicated and integrated server."
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.moonrise]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moonrise]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moonrise]]
modId = "starlight"
type = "incompatible"

[[dependencies.moonrise]]
modId = "lithium"
type = "incompatible"

[[dependencies.moonrise]]
# unofficial lithium port
modId = "canary"
type = "incompatible"

[[dependencies.moonrise]]
# unofficial lithium port
modId = "radium"
type = "incompatible"

[[dependencies.moonrise]]
modId = "c2me"
type = "incompatible"

[[mixins]]
config = "moonrise.mixins.json"

[[mixins]]
config = "moonrise-neoforge.mixins.json"
